import Head from "next/head";
import {Task} from "src/interfaces/taks";
import TasksGallery from "src/components/TasksGallery";
import { useRouter } from "next/router";

interface Props {
  tasks: Task[];
}

export default function Home({tasks}: Props) {
  const router = useRouter()
  return (
    <>
        <Head>
          <title>Notas</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
<section>
  {tasks.length ===0 
  ? <h1>No hay tareas</h1> 
  : <TasksGallery tasks={tasks}></TasksGallery>}
  
</section>
<p onClick={()=>{router.push('/new')}}>
  Create a new one
</p>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/tasks");
  const tasks = await res.json();
  return {
    props: {
      tasks: tasks,
    },
  };
};
