import Head from "next/head";
import {Task} from "src/interfaces/taks";

import FormNewTask from "src/components/FormNewTask";
import TasksGallery from "src/components/TasksGallery";

interface Props {
  tasks: Task[];
}

export default function Home({tasks}: Props) {
  return (
    <>
        <Head>
          <title>Notas</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
<section>
  {tasks.length ===0 
  ? <h1>No hay tareas</h1> 
  : <TasksGallery tasks={tasks}></TasksGallery>}
  
  <FormNewTask />
</section>

    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/tasks");
  const tasks = await res.json();
  return {
    props: {
      tasks: tasks,
    },
  };
};
